### ISSUE TITLE
Пресичане на правоъгълници

### ISSUE THREAD

**Issue by dibash** [IvanFilipov/FMI-OOP#2]
Ако някоя точка от единия правоъгълник се съдържа в другия, то те се пресичат, но обратното не е така. Ето пример:
![rect](https://user-images.githubusercontent.com/16972596/37231410-c73e26aa-23f3-11e8-88fe-d58a589a899c.png)

**Comment by IvanFilipov** [comment]
Прав си, дай предложение да го оправим :)
